[package]
name = "icp_rust_boilerplate_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.6"
ic-cdk-macros = "0.6"
serde = { version = "1.0", features = ["derive"] }
candid = "0.8"
ic-stable-structures = "0.1.0"
